[package]
name = "actix_sqlx_mysql"
version = "0.1.0"
authors = ["huiali <huiali@hotmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
